---

composer_path: /usr/local/bin/composer
composer_update: true
composer_update_day: 20
composer_path_env: False
#composer_home_path: /opt/composer
composer_home_owner: root
composer_home_group: root
composer_global_packages:
  phpunit:
    name: phpunit/phpunit
    version: "^5.4.0"
  codeception:
    name: codeception/codeception
    version: "~2.2.7"
  phpspec:
    name: phpspec/phpspec
    version: "~3.2.2"
  phpcs:
    name: squizlabs/php_codesniffer
    version: "~2.7.1"
proxy_env: {}

# Visit https://github.com/settings/applications 
# and generate personal access token
composer_github_oauth: false
