---

- include: install.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-install

- include: config.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-config

- include: ssh-known-hosts.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-known-hosts

- include: service.yml
  tags:
    - system
    - networking
    - ssh
    - ssh-service
